### ISSUE TITLE
BackStats

### ISSUE THREAD

**Issue by SeanPoints** [kslong/kred#14]
BackStats.py is only finding matches for filter N662 for LMC_c50.  The directory DECam_BACK/LMC_c50/T?? contains data for all filters (N662, N673, 708, and r).

**Comment by kslong** [comment]
@SeanPoints  Do you mean that it appears to run OK, but does not. Or are any errors produced.  Also, in future please give the branch and commit number

**Comment by SeanPoints** [comment]
Main branch/commit 372bec85791dfa4185a74533a950cc6cc97dfd2f (I downloaded these last Friday - 23 June).  Program returns:
[2023-06-30 16:45:02] Current commit: 372bec85791dfa4185a74533a950cc6cc97dfd2f
[2023-06-30 16:45:02] BackStats: Starting LMC_c50 T01
Finished   3 x-matches for  DECam_BACK/LMC_c50/T01/c4d_190106_055922_ooi_N662_v1_N20.fits 
Finished   2 x-matches for  DECam_BACK/LMC_c50/T01/c4d_190106_055922_ooi_N662_v1_N25.fits 
Finished   3 x-matches for  DECam_BACK/LMC_c50/T01/c4d_190106_064056_ooi_N662_v1_N14.fits 
Finished   3 x-matches for  DECam_BACK/LMC_c50/T01/c4d_190106_064056_ooi_N662_v1_N15.fits 
Finished   4 x-matches for  DECam_BACK/LMC_c50/T01/c4d_190106_064056_ooi_N662_v1_N20.fits 
Finished   2 x-matches for  DECam_BACK/LMC_c50/T01/c4d_190106_064056_ooi_N662_v1_N25.fits 
Finished   7 x-matches for  DECam_BACK/LMC_c50/T01/c4d_190106_072229_ooi_N662_v1_N20.fits 
Finished   6 x-matches for  DECam_BACK/LMC_c50/T01/c4d_190106_072229_ooi_N662_v1_N25.fits 
Finished   4 x-matches for  DECam_BACK/LMC_c50/T01/c4d_190106_080400_ooi_N662_v1_N14.fits 
Finished   6 x-matches for  DECam_BACK/LMC_c50/T01/c4d_190106_080400_ooi_N662_v1_N15.fits 
Finished   8 x-matches for  DECam_BACK/LMC_c50/T01/c4d_190106_080400_ooi_N662_v1_N20.fits 
Wrote Summary/LMC_c50_T01_xxx.txt with 48 lines
[2023-06-30 16:46:14] BackStats: Finished LMC_c50 T01

Does not give any error messages for N673, N708, or r filters.

**Comment by kslong** [comment]
@SeanPoints  I am unable to reproduce this error on the back branch.  Please download the latest version of the back branch, and create a pristine environment for running kred.  Then run the following sequence of commands.  

````
# MefSum.py LMC_c50
# MefPrep.py LMC_c50
SetupTile.py LMC_c50 T01
SwarpSetup.py LMC_c50 T01
Swarp.py LMC_c50 T01
FindOverlaps.py LMC_c50 T01
BackPrep.py -run LMC_c50  T01
BackStats.py -np 12 -rm LMC_c50 T01
BackCalc.py LMC_c50 T01
BackSub.py -np 12 LMC_c50 T01
SwarpSetup.py -bsub LMC_c50 T01
Swarp.py -bsub LMC_c50 T01
SwarpEval.py LMC_c50 T01  T01_b
````
You will likely need to run MefSum and MefPrep again, because a few things have changed there.  Depending on your conda environment, you may also need to set up a new one, as Rick has used some recent features of numpy. There are instructions in the README file for how to do this.

**Comment by kslong** [comment]
If the above steps still fail, please make a tar file of your Summary directory, and put it here so I can compare it with the one that I made when I ran the steps above.

**Comment by SeanPoints** [comment]
If I understand the procedure, 
(1) Maybe clone everything into new directory (git clone git@github.com:kslong/kred)
(2) git fetch
(3) git checkout back
Anything else I should do?

**Comment by kslong** [comment]
No, that is not what I meant.  Your current git  repository is fine.  You should do git fetch and git checkout back, like normal.  You only have to clone a new version of the entire repository if yours has gotten messed up.

But you should create a new directory for  running the code, e.g ktest,  because I don't want any of your old processing to have be involved.  ISet up that directory up so you can run the S/W by linking to the MEF directory.  Then run the commands I suggested starting with MefSetup.py

**Comment by SeanPoints** [comment]
I'm in a new workspace with branch set to back.

**Comment by SeanPoints** [comment]
Successfully reduced field LMC_c50 through all step using back branch.  Closing issue
