### ISSUE TITLE
MefPrep.pf failure field LMC_c38

### ISSUE THREAD

**Issue by SeanPoints** [kslong/kred#15]
Branch: back
Commit: b6f3289e4daedc51aea4f44a7e1980c8ea27cbb6

Began processing file c4d_190108_063145_ooi_N662_v1
Runtime error: decompression error: hit end of compressed byte stream

Checked the MEF fits image and it gave message: "Fitsy++ rice bad inflate" and only showed 3 detectors.  It may be a bad FITS file from the archive.  Going to move it out of the MEF directory when I can.

**Comment by kslong** [comment]
@SeanPoints  I looked, and I may have seen this error also.  I will try running this mañana, also. I want to figure out how to throw an error that we see, but that get's past it.

**Comment by kslong** [comment]
I am testing the fix that I suggested above, on all of LMC_c38

**Comment by kslong** [comment]
@SeanPoints   Are you still seeing this error.  If you are not could you please close the issue.  If you are still seeing it, please provide a bit more information.

**Comment by kslong** [comment]
To check whether this is really solved. One needs to have the MEF file above in the DECam_MED directory.  For the recent data that is no longer the case, so it may not be surprising that I am not seeing the error anymore.  Presumably the file is in one of the old versions that is on Box.

**Comment by kslong** [comment]
I downloaded the oldest version of the data that is on Box, and ran the current version of kred on LMC_c48 through the MefPrep stages and the file that was associated with this exposure (and all of the other files run fine).  These files files have the extension _req, instead of v1.  My guess is that something did fail in the original processing of the data, that was corrected when the data were reprocessed.  One could verify this by re-retrieving the data from the NOIRLAB archive, but this seems not worth the trouble.  I am closing the issue; if a new problem appears, we can deal with it then.
